### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by fxlui** [imnotpopo/movietickets#1]
@DoctorChe hi can i ask why you starred my program earlier? thanks

**Comment by imnotpopo** [comment]
lol im just curious

**Comment by DoctorChe** [comment]
Hi! I am just learning python. So I was surfing for some examples. And your app looks cool!

**Comment by fxlui** [comment]
Oh haha thanks! I'm still a beginner so be sure to tell me if you spot any errors!
